version: "3.7"

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo


  blog:
    image: registry.cn-hangzhou.aliyuncs.com/xjh2000/blog
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8080:8080"

  redis:
    image: redis
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup




volumes:
  mongo_db: