version: "3.0"

services:

    caddy:
        image: caddy
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ~/app/caddy/Caddyfile:/etc/caddy/Caddyfile
            - ~/app/caddy/caddy_data:/data
            - ~/app/caddy/caddy_config:/config

    free-movie-server:
        image: 934622645/free-movie-server
        restart: unless-stopped

    mysql:
        image: mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
        restart: unless-stopped
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "free_movie"

    watchtower:
        image: containrrr/watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 60 --cleanup

volumes:
    mysql_data: