version: "3.3"

services:

  halo:
    image: halohub/halo
    volumes:
      - ~/app/halo:/root/.halo
    restart:
      unless-stopped
    expose:
      - 8090
    tty:
      true
    stdin_open:
      true

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/app/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ~/app/caddy/caddy_data:/data
      - ~/app/caddy/caddy_config:/config
