version: "3.9"

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "~/app/mongo:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  movie-service:
    image: registry.cn-hangzhou.aliyuncs.com/xjh2000/movie
    restart: always
    expose:
      - "8000"

  halo:
    image: halohub/halo:1.5.0-alpha.3
    volumes:
      - ~/app/halo:/root/.halo
    restart:
      unless-stopped
    expose:
      - 8090
    tty:
      true
    stdin_open:
      true

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/app/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ~/app/caddy/caddy_data:/data
      - ~/app/caddy/caddy_config:/config
