version: "3.7"

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql


  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: blog


  blog:
    image: registry.cn-hangzhou.aliyuncs.com/xjh2000/blog
    restart: on-failure
    environment:
      - MONGO_URI=mongodb://mongo:27018
    ports:
      - "8080:8080"

  redis:
    image: redis
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup




volumes:
  mongo_db:
  mysql-db: