version: "3.1"

services:

    postgres:
        image: postgres:14.2
        restart: always
        expose:
            - 5432
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=quarkus


    redis:
        image: redis:6-alpine
        restart: always
        ports:
            - "6379:6379"

volumes:
    postgres_data:
