version: "3.7"

services:

  wechat:
    image: registry.cn-hangzhou.aliyuncs.com/xjh2000/wechat
    restart: on-failure
    ports:
      - "8888:8080"

  redis:
    image: redis
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup