version: "3.1"

services:

  halo:
    image: halohub/halo
    volumes:
      - ~/app/halo:/root/.halo
    restart:
      unless-stopped
    ports:
      - "8000:8090"
    tty:
      true
    stdin_open:
      true
