version: "3.1"

services:

  halo:
    image: halohub/halo:1.5.0-alpha.3
    volumes:
      - ~/app/halo:/root/.halo
    restart:
      unless-stopped
    expose:
      - 8000
    tty:
      true
    stdin_open:
      true


  frp-client:
    image: snowdreamtech/frpc
    network_mode: "host"
    restart: always
    volumes:
      - ~/app/frp/frpc.ini:/etc/frp/frpc.ini