version: "3.1"

services:

    mongo:
        image: mongo:4.4.13
        restart: always
        expose:
            - 27017
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
    redis:
        image: redis:6-alpine
        restart: always
        ports:
            - "6379:6379"

volumes:
    mongo_data:
