version: "3.1"

services:

  halo:
    image: halohub/halo
    volumes:
      - ~/app/halo:/root/.halo
    restart:
      unless-stopped
    ports:
      - "8000:8090"
    tty:
      true
    stdin_open:
      true


  frp-client:
    image: snowdreamtech/frpc
    network_mode: "host"
    restart: always
    volumes:
      - ~/app/frp/frpc.ini:/etc/frp/frpc.ini