version: "3.3"

services:

  halo:
    image: halohub/halo:1.5.0-alpha.3
    volumes:
      - ~/app/halo:/root/.halo
    restart:
      unless-stopped
    expose:
      - 8090
    tty:
      true
    stdin_open:
      true

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/app/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ~/app/caddy/caddy_data:/data
      - ~/app/caddy/caddy_config:/config


  frps:
    image: snowdreamtech/frps
    ports:
      - "7000:7000"
    restart:
      unless-stopped
    volumes:
      - ~/app/frp/frps.ini:/etc/frp/frps.ini